# Generated by Django 5.0.2 on 2024-02-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSLClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GSLCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_carga', models.CharField(choices=[('Importacion', 'Importacion'), ('Exportacion', 'Exportacion')], max_length=255)),
                ('actividad_carga', models.CharField(choices=[('Marítimo', 'Marítimo'), ('Aéreo', 'Aéreo'), ('Terrestre', 'Terrestre')], max_length=255)),
                ('fecha_arribo', models.DateTimeField()),
                ('vencimiento_almacenaje', models.DateTimeField()),
                ('estado_actual', models.CharField(choices=[('Notificada', 'Notificada'), ('En proceso', 'En proceso'), ('Entregada', 'Entregada'), ('Cobrada', 'Cobrada')], max_length=255)),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsl_cargo.gslclientes')),
            ],
        ),
        migrations.CreateModel(
            name='GSLGastosCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gasto', models.CharField(max_length=255)),
                ('total_gasto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsl_cargo.gslcargo')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsl_cargo.gslclientes')),
            ],
        ),
        migrations.CreateModel(
            name='GSLPapeleriaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arribo', models.DateField()),
                ('tipo_papeleria', models.CharField(max_length=255)),
                ('id_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsl_cargo.gslcargo')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsl_cargo.gslclientes')),
            ],
        ),
    ]
