# Generated by Django 5.0.2 on 2024-02-28 22:21

import gsl_cargo.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsl_cargo', '0002_alter_gslpapeleriacargo_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gslgastoscargo',
            name='archivo',
            field=models.FileField(default='', upload_to=gsl_cargo.utils.gastos_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gslpapeleriacargo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=gsl_cargo.utils.papeleria_upload_to),
        ),
    ]
