# Generated by Django 5.0.2 on 2024-02-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsl_cargo', '0003_gslgastoscargo_archivo_gslpapeleriacargo_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gslpapeleriacargo',
            name='fecha_arribo',
        ),
    ]
