# Generated by Django 5.0.2 on 2024-02-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsl_cargo', '0004_remove_gslpapeleriacargo_fecha_arribo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gslgastoscargo',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GTQ', 'GTQ')], default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
