# Generated by Django 5.0.2 on 2024-02-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsl_cargo', '0005_gslgastoscargo_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gslcargo',
            name='fecha_arribo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gslcargo',
            name='vencimiento_almacenaje',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
