# Generated by Django 5.0.2 on 2024-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsl_cargo', '0007_gslcargo_bl_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gslcargo',
            name='naviera',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
