# Generated by Django 5.0.2 on 2024-03-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsl_cargo', '0008_gslcargo_naviera'),
    ]

    operations = [
        migrations.AddField(
            model_name='gslcargo',
            name='demora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
